#!/bin/bash

# This script is intended to run composer and DB migrations on Sainsbury's HARA-repositories.
#
# Created by: Salman Ahmed
# Creation date: 12 July 2016

## Set necessary variables first
startDir="$PWD"
haraOpsDir="$PWD/../hara-ops/"
haraRepoDir=${PWD##*/}
vagrantDir="${haraOpsDir}cookbooks/sainsburys-hara/.kitchen/kitchen-vagrant/kitchen-sainsburys-hara*"

## We only need to run this script for HARA - BE services
# Check if $haraRepoDir is a valid hara repo (it starts with `hara` and ends with `service)
if ! [[ $haraRepoDir =~ ^hara.*service ]] ; then
	exit;
else
	echo "'$haraRepoDir' is a valid hara back-end repo.";
fi

echo '';
echo ">>>> PWD: '$startDir' <<<<";
echo ">>>> HARA Ops dir: '$haraOpsDir' <<<<";
echo ">>>> HARA BE service repo dir: '$haraRepoDir' <<<<";
echo '';

echo "~~~ Script for 'composer install' and 'database migrations' ~~~";

echo "Doing composer install...";
composer install;
echo '';

## In order to do database migrations we need to ssh into the machine and run `phinx migrate` command
## SSH into HARA-VM and do DB migrations

echo "Changing dir to '$vagrantDir' so we can SSH into HARA-VM";
cd $vagrantDir;


echo 'Doing DB migrations...';
vagrant ssh -c "cd /hara/$haraRepoDir/; ./vendor/bin/phinx migrate;"
echo '';

## cd back to the original directory we started
cd $startDir;

echo "==========~~~It's all done---Finito~~~============";
echo '==========~~~~~~~~Happy coding~~~~~~~~============';
echo '==========~~~~Script by salmander~~~~~============';
